"""initial schema

Revision ID: 4c681967b297
Revises: 
Create Date: 2026-03-07 08:35:46.531939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c681967b297'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irb_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('study_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('communication_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.String(length=100), nullable=False),
    sa.Column('referring_provider', sa.String(length=200), nullable=True),
    sa.Column('referral_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='referralstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='outreachstatus'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outreach_job_id', sa.Integer(), nullable=False),
    sa.Column('twilio_call_sid', sa.String(length=100), nullable=True),
    sa.Column('outcome', sa.Enum('ANSWERED', 'VOICEMAIL', 'NO_ANSWER', 'BUSY', 'FAILED', name='calloutcome'), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('final_state', sa.Enum('IDENTITY_VERIFICATION', 'INTRODUCTION', 'PRE_SCREEN', 'SCHEDULING', 'ESCALATION', 'COMPLETED', name='conversationstate'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outreach_job_id'], ['outreach_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twilio_call_sid')
    )
    op.create_table('pre_screen_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_session_id', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_value', sa.String(length=200), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_screen_responses')
    op.drop_table('call_sessions')
    op.drop_table('outreach_jobs')
    op.drop_table('referrals')
    op.drop_table('patients')
    op.drop_table('irb_knowledge')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
